### ISSUE TITLE
Please register a bower package

### ISSUE THREAD

**Issue by sgtpep** [xgbuils/lazyarray-lite#1]
It would be really appreciated, if this nice class will be available through bower, not only npm.

**Comment by xgbuils** [comment]
Thanks for your suggestion

I don't usually use `Bower`. What should I put in a `main` field of `bower.json`? A minified source or no minified?

**Comment by sgtpep** [comment]
As far as I can tell, some packagers put the both versions, but others put only not minified version. And it's OK, because package consumers can minify it by themselves, if they need to.

**Comment by xgbuils** [comment]
I created a `bower` [new gulp task](https://github.com/xgbuils/lazyarray-lite/commit/2054d52811e1b99143c5a0282d7d3f0798f8cc6a) that builds source for browsers in `dist/` directory. I created [bower lazyarray-lite project](https://github.com/xgbuils/bower-lazyarray-lite) in `dist/` and published to `bower`.

You can use:

``` bash
$ bower install lazyarray-lite
```

Now it just works for global context. Now I don't have much time. If you agree, you could make a PR to improve it(documentation, AMD context). :)

**Comment by sgtpep** [comment]
Thank you very much for your time and efforts! I hope that more frontend devs could dicover your lib. It's invaluable for writing tests and generating fake large datasets.
